# The following are pulled from env variables
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  [
    {
      'source': 'packages/scenes/src/locales/en-US/grafana-scenes.json',
      'translation': 'packages/scenes/src/locales/%locale%/%original_file_name%',
      'type': 'i18next_json',
    },
  ]
