name: Crowdin automatic task management

on:
  workflow_dispatch:
  # once a month on the first day of the month at midnight
  schedule:
    - cron: "0 0 1 * *"

jobs:
  create-tasks-in-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-create-tasks.yml@19d18645acffb1974ff27db6d40333aa01a0d490 # main
    with:
      crowdin_project_id: 34
