name: Crowdin Upload Action

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/scenes/src/locales/en-US/grafana-scenes.json'
    branches:
      - main

jobs:
  upload-sources-to-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-upload.yml@19d18645acffb1974ff27db6d40333aa01a0d490 # main
    with:
      crowdin_project_id: 34
