name: Verify i18n markup has been committed

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-i18n:
    uses: grafana/grafana-github-actions/.github/workflows/verify-i18n.yml@36cd995b957c918d9f7c83953149d2507a53c2fd # main
