name: Crowdin Upload Action

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/scenes/src/locales/en-US/grafana-scenes.json'
    branches:
      - main

jobs:
  upload-sources-to-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-upload.yml@6606a86307be7d0f4249bc38a19a5f5818d2cd55 # main
    with:
      crowdin_project_id: 34
