name: "publish-technical-documentation-next"

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/sources/**"
  workflow_dispatch:
jobs:
  sync:
    if: "github.repository == 'grafana/scenes'"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Clone website-sync Action"
        # WEBSITE_SYNC_TOKEN is a fine-grained GitHub Personal Access Token that expires.
        # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
        # GitHub administrator to update the organization secret.
        # The IT helpdesk can update the organization secret.
        run: "git clone --single-branch --no-tags --depth 1 -b master https://grafanabot:${{ secrets.WEBSITE_SYNC_TOKEN }}@github.com/grafana/website-sync ./.github/actions/website-sync"

      - name: "Rsync docusaurus files"
        run: |
          rsync -av docusaurus/docs/{getting-started,core-concepts}.md docs/sources/getting-started/
          rsync -av docusaurus/docs/{advanced-custom-scene-objects,advanced-activation-handlers,advanced-data,advanced-variables}.md docs/sources/advanced-usage/
          rsync -av docusaurus/docs/{visualizations,variables,transformations}.md docs/sources/scene-objects/
          rsync -av docusaurus/docs/{scene-app-tabs,scene-app-drilldown}.md docs/sources/scene-objects/scene-app/

      - name: "Publish to website repository (next)"
        uses: "./.github/actions/website-sync"
        id: "publish-next"
        with:
          repository: "grafana/website"
          branch: "publish-scenes-to-website"
          host: "github.com"
          # PUBLISH_TO_WEBSITE_TOKEN is a fine-grained GitHub Personal Access Token that expires.
          # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
          # GitHub administrator to update the organization secret.
          # The IT helpdesk can update the organization secret.
          github_pat: "grafanabot:${{ secrets.PUBLISH_TO_WEBSITE_TOKEN }}"
          source_folder: "docs/sources"
          target_folder: "content/docs/scenes/next"
